server {
    listen 3000;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy al BFF-Web para evitar CORS
    location /bff/ {
        proxy_pass http://bff-web:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # React Router: redirige todo al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
