server.port=8086
spring.application.name=ms-archivos
spring.datasource.url=jdbc:postgresql://postgres-archivos:5432/db_archivos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.minio.endpoint=http://minio:9000
spring.minio.accessKey=minioadmin
spring.minio.secretKey=minioadmin
spring.minio.bucket-name=archivos